export const DELETE_COMMENT = 'DELETE_COMMENT';
export const SET_EDITABLE_COMMENT = 'SET_EDITABLE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const CANCEL_EDITING = 'CANCEL_EDITING';
export const GET_COMMENTS = 'GET_COMMENTS';